### ISSUE TITLE
slater question

### ISSUE THREAD

**Issue by eballeste** [the-couch/slater#10]
Wondering what you guys meant with:
> This project is an active work in progress! The CLI is stable, *but the theme itself is not*.

What's missing from the theme itself that you would consider it unstable?

**Comment by iamkevingreen** [comment]
Hey @eballeste, the theme has actually recently seen some love. I think it's more our internal conflict to either build out more of the theme in our opinionated way or try to keep it simple. The goal of this project is really for us internally to quickly bootstrap Shopify sites that have all the bells and whistles that we add to our experiences. 

The parts of the theme that were unstable and have since been updated were the accounts and basic add to cart/ajax cart functionality. That has all been updated so it's not in the worst place. However if you are expecting the theme to do things for you and you run into issues it's sort of up to you to handle those situations. This is by no means a beginner friendly starter theme. The theme assumes you have a good grasp of the Shopify Architecture as well as a good grasp of liquid/js/css.

As a result the disclaimer for the actual theme is more `use at your own risk`  (not that it's a large risk but you get the idea). As a result you could use just the build tools or drop your in your own src theme, theres nothing stopping you from doing that but you'll lose out on some of the initial bootstrapping that the theme does offer.

I'll leave this open as a conversation around this topic.

**Comment by eballeste** [comment]
amazing, thank you for prompt response, I think I'm going to take slater out for a spin 👌
