### ISSUE TITLE
Issue with Slater Sync

### ISSUE THREAD

**Issue by callummcmaugh** [the-couch/slater#111]
I'm unsure if slater sync works on Windows. I have a pipeline using a linux image and has no issues building and deploying the theme to a staging theme. But I'm attempting to use this locally too to update my development theme from changes on other git branches/ development themes in a team.

However, I get no result on the sync process.
```
slater v1.8.0
slater synced development theme (https://****/?fts=0&preview_theme_id=*****)
```

My workaround is to clone the staging theme and update my development id to the new theme, but if I could use slater to sync themes, that would be great.

**Comment by jack-pallot** [comment]
You might have more luck running [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) if you're on Windows. Then you'll have access to a Unix-based command line.

**Comment by MLCochrane** [comment]
I believe it's to do with the [sanitize](https://github.com/the-couch/slater/blob/master/packages/util/sanitize.js#L7) utility function.
When generating the new file paths they are split with a `/` so Windows-specific paths end up returning `null`.

`return sanitize(p.split('/').slice(1).join('/'))`

Perhaps adding a string replace `p.replace(/\\/g, '/');` would be enough to catch this?

Also wonder if the regex test could benefit from being a single match instead of being called recursively, but that could be a separate issue.

**Comment by callummcmaugh** [comment]
Installing Linux subsystem on Windows had resolved this for me.
