### ISSUE TITLE
page title becomes 'undefined' after route change

### ISSUE THREAD

**Issue by seandogg** [the-couch/slater#125]
Not sure if this is an issue for operator, but with any fresh install of a Slater theme, anytime I make a route change to another URL, I'll get `undefined` as the page title -- specifically showing most obviously in the browser tab of the Slater theme. 

This has become true with any older slater theme that I've updated too. 

My immediate workaround is adding this to `router.js`: 

`
const router = operator('#root', [
  {
    "path": "/*",
     ignore: true
  }
  `
  
Has anyone else experienced similar? Thanks in advance

**Comment by adamrasheed** [comment]
Having the same issue @iamkevingreen any insight?

**Comment by iamkevingreen** [comment]
@adamrasheed & @seandogg it's related to the context of the page title, I don't have the `slater` solution here, but what I did on another site with operator was put a data-page-title attribute inside of the content that shows up within the root (within the main page context). I grab that title onAfter and push that tag in. 

I think it's specifically how operator is finding the title within context and not really related to slater exactly but since we're using operator that's what's happening on route changes.

**Comment by bekahmcdonald** [comment]
Looks like `operator v1.7.0` might have introduced [a breaking change](https://github.com/estrattonbailey/operator#v170).

In `scripts/router.js`, you now need to use `previousDocument.title` instead of `title`(and update the params).

```javascript
router.on('after', ({ previousDocument, pathname}) => { // Update the parameters to use previousDocument
  document.title = previousDocument.title; // Use previousDocument.title here
  window.history.pushState({}, '', pathname);
});

**Comment by m-w-d-d** [comment]
Thanks @bekahmcdonald - I was just looking into this and you've saved me a job. Thanks!

**Comment by seandogg** [comment]
Going to go ahead and close as @bekahmcdonald is awesome and this fix is working.
