### ISSUE TITLE
How to include fonts files

### ISSUE THREAD

**Issue by reco** [the-couch/slater#4]
Loader missing for binary font files

`error ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)`

**Comment by iamkevingreen** [comment]
@reco we'll most likely not wrap this into our build pipeline and instead rely on Shopify assets directory. We'll be sure to include an example of an open source font in the theme so that it's easier to understand!

**Comment by reco** [comment]
hey @iamkevingreen i agree. the problem here is that accessing the font-file relative produces that error. 

```@font-face {
  font-family: "BeaufortExtendedMedium";
  src: url("37DFB8_0_0.eot");
  src: url("37DFB8_0_0.eot?#iefix")
      format("embedded-opentype"),
    url("37DFB8_0_0.woff2") format("woff2"),
    url("37DFB8_0_0.woff") format("woff"),
    url("37DFB8_0_0.ttf") format("truetype");
}```

**Comment by iamkevingreen** [comment]
@reco What we recommend is creating a fonts.css.liqiud file in the assets directory. Sorry if that wasn't clear. We don't handle the importing because of the way shopify creates it's asset urls, you should instead have something like the following:

```
@font-face {
  font-family: 'Plaid-XS-Web';
  font-weight: 400;
  font-style: normal;
  src: url('{{ 'Plaid-XS.eot' | asset_url }}');
  src: url('{{ 'Plaid-XS.eot?#iefix' | asset_url }}') format('embedded-opentype'),
       url('{{ 'Plaid-XS.woff2' | asset_url }}') format('woff2'),
       url('{{ 'Plaid-XS.woff' | asset_url }}') format('woff');
}
```
The fonts should be placed in the `assets` directory, and the `fonts.css.liquid` should also be in the `assets` directory because you need to pull the urls in a Shopify way. 

Then of course in your theme.liquid something as simple as such in the header next to our css:

```
    {{ 'fonts.css' | asset_url | stylesheet_tag }}
    {{ 'main.css' | asset_url | stylesheet_tag }}
```

**Comment by waywardm** [comment]
could you not use https://github.com/KyleAMathews/typefaces

which uses npm to pull in google typefaces

**Comment by iamkevingreen** [comment]
@waywardm you could do that, but we'd also not want to add additional deps for the sake of google type faces, most our projects are custom type faces. Additionally nothing is stopping you from using this on your own?

**Comment by estrattonbailey** [comment]
Our goal with this project is to keep as much opinion and bloat out of the core codebase and emphasize simplicity.

Since adding fonts using a separate `fonts.css.liquid` file is so easy, that's our recommendation for the near future. We've discussed a few other options, and would be open to PRs!

@waywardm in regard to the `typefaces` package, we encourage you to try it out! Ideally our end users are free to augment their sites as they like, so if something about our build process breaks that package, shoot us a more specific issue and we'll try to fix it :)
