### ISSUE TITLE
Shopify Apps (product reviews) need a manual refresh to be loaded on the product template?

### ISSUE THREAD

**Issue by seandogg** [the-couch/slater#43]
Not sure if this was intended to be addressed in [16](https://github.com/the-couch/slater/issues/16), but I'm seeing that a couple apps my client uses (Wishlist and Shopify Reviews) aren't being loaded on the product.liquid template without a manual reload of the page. Guessing there's a simple fix perhaps and maybe someone can point me there.

**Comment by iamkevingreen** [comment]
@seandogg we use pjax (page ajax), so that means any javascript on the page has to be reloaded. (hence the hard refresh). Various plugins provide functions for refreshing these aspects. 

For example with Yotpo in our product component JS we have things like:

```
var api = new Yotpo.API(yotpo)
api.refreshWidgets()
```

If the plugins you're using don't provide this ability to refresh the gui then you can programmatically not use the ajax on pages that need to hard refresh by adding `no-ajax` to the anchor tags linking to those pages.
