### ISSUE TITLE
Further maintenance

### ISSUE THREAD

**Issue by rafaelderolez** [the-couch/slater#69]
Hey 👋

Just wondering if there will be any maintenance from the-couch owners at all in the future? I noticed on your website the agency has unfortunately closed down :(

Might be useful to put out a 'looking for maintainers message' if necessary.

**Comment by iamkevingreen** [comment]
The Couch wasn't really the traditional agency in this case, I am still using this and as long as people ask me to work on Shopify sites (which they continue to), I will make updates. Might toss up a looking for maintainers or just more contributors. Someone already forked it and is extending just the build tools which is awesome. 

Hoping to actually grab some of what he has been doing when I have a little bit more downtime. I did jusssst build another site with slater this past month so it's still in working operation :)

Got a few ideas for updating things, I know that slate actually improved their option selecting and I'd love to bring that into slater because I think ours is a bit overly complicated right now. 

Hopefully have some time in Dec to push some more updates into the theme, but the build process is still good to go!

**Comment by knockawes** [comment]
Just wanted to quickly ask here if Slater will function properly with Shopify's new section themes:

https://help.shopify.com/en/themes/development/section-themes

Thanks for everything you've built here Kevin.

**Comment by iamkevingreen** [comment]
@knockawes Yeah I am mostly waiting for it to come out of the beta stage, but also been doing a lot of headless sites because of the current limits of the cms in Shopify. Plan on releasing a Gatsby+Shopify thing in the coming month or so as well that also plays off the current Slater store instance.

**Comment by iamkevingreen** [comment]
Closing this out as it was only a question that I feel like I answered. Have had some time to make various updates to the theme as well and would love to get any input from people that have been using it for projects.
