### ISSUE TITLE
Issue loading scripts on product page

### ISSUE THREAD

**Issue by alejuu** [the-couch/slater#70]
Hi, I have a question. I'm trying to include a JS carousel library for the product images, but I'm having a problem. I don't know if I understand the correct way to include libraries or run scripts in specific pages.  At the moment I'm adding my code in src/scripts/index.js
My code:
```
import { tns } from '../../node_modules/tiny-slider/src/tiny-slider'
const slider = tns({
  container: '.product-slider',
  items: 1,
  slideBy: 'page',
  autoplay: true,
  mouseDrag: true
})
```
It works, the problem is that it only works if I refresh the site or if I land on a product page. I'm guessing this is because of the Router. My question is, what is the best way to include other libraries and scripts? It's not to clear to me on the documentation (maybe I'm not understanding). Also, I'm more used to the old way of creating Shopify themes, and I'm still learning to adapt.

**Comment by iamkevingreen** [comment]
You'll want to use the `app.js` to import js, if you import directly into the index you have to remount the application.

Anything loaded in via picoapp is remounted on all route changes, alternatively you could disable operator and all js will remount without doing animate page transitions:

https://github.com/the-couch/slater/blob/master/packages/theme/src/scripts/index.js#L20 (the remounting that happens if you use the picoapp for mounting scripts)

**Comment by alejuu** [comment]
Thanks, @iamkevingreen.
