### ISSUE TITLE
Variant images

### ISSUE THREAD

**Issue by jrandallw** [the-couch/slater#78]
Hello. Since there’s no selectCallback() built into this theme, is there anywhere you can point me to in order to add swatches and changing variant images to the theme?

Thank you!

**Comment by iamkevingreen** [comment]
The way we handle this is so per theme basis, many clients want more than 1 image per variant which almost always requires a hack, we either do this with metafield plugins or custom named file attributes. It's why we didn't cake any of this into the theme itself because it would be far to opinionated + specific to whatever out use case would be. 

Many also want this to be a slideshow so if we simply had it update the image on variant select it would be an hurdle as well. I don't really have any good example references, since most the code is custom in client specific experiences. If you've come up with an example template I'd be happy to PR it for others to see.
